aleksei: homework 5 completed
eugene-okulik/Hozeri pull request #4
Opened 2024-11-27 23:17 UTC by Hozeri

2024-11-28 06:49 UTC, eugene-okulik requested changes

2024-11-28 06:49 UTC, eugene-okulik commented on homework/aleksei_karev/homework_5/task_3.py
> +subjects_text = f'subjects: {subjects[0]}, {subjects[1]}, {subjects[2]}'
Обращаться к элементам списка по индексу - полсднее дело. Так делают, если по-другому вообще никак. Здесь отлично бы подошел подход с `join`. Такой подход еще и универсальный - если в списках будет другое количество элементов, все элементы будут получены без проблем.

2024-11-28 11:02 UTC, Hozeri commented on homework/aleksei_karev/homework_5/task_3.py
> +subjects_text = f'subjects: {subjects[0]}, {subjects[1]}, {subjects[2]}'
Спасибо! У меня почему-то вылетел этот метод из головы, когда делал дз. Вернусь домой с работы и поправлю ;-)

2024-11-29 06:53 UTC, eugene-okulik approved these changes

2024-11-29 06:53 UTC, merged